version: "3.8"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    restart: unless-stopped
    tty: true
    environment:
      DB_HOST: db
      DB_DATABASE: taxiapi
      DB_USERNAME: root
      DB_PASSWORD: root
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
    depends_on:
      - db
    networks:
      - app

  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    volumes:
      - ./client:/var/www/html/
    networks:
      - app

  webserver:
    depends_on:
      - server
      - client
    build:
      context: ./server/nginx
      dockerfile: Dockerfile
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    networks:
      - app

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    tty: true
    networks:
      - app
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taxiapi
    volumes:
      - /dbdata/var/lib/mysql/
      - ./sql/db_taxiapi.sql:/docker-entrypoint-initdb.d/db_taxiapi.sql:ro

networks:
  app:
    driver: bridge
